% =========================================================================
% IEEE SP CUP 2026 - EVALUATION SCRIPT (OSINR + ViSQOL)
% =========================================================================
clear; clc; close all;

%% 1. CONFIGURATION
% -------------------------------------------------------------------------
% Path to the dataset (containing target.wav, interference.wav, mixture.wav)
% Matches the path used in main.m
dataDir = "/home/cse-sdpl/ramakrishna/real-time-audio-visual-zooming/modal_solutions/IRM_TFLC/python/data/simulated/batch_test_000/";

% Path to the processed output (generated by main.m)
outDir  = "../output/";
processed_file = fullfile(outDir, "output_raw_mask.wav"); % or output_gauss_mask.wav

% Ground Truth Files
files.target = fullfile(dataDir, "target.wav");
files.interf = fullfile(dataDir, "interference.wav");
files.mix    = fullfile(dataDir, "mixture.wav");

%% 2. LOAD AUDIO
if ~isfile(processed_file) || ~isfile(files.target)
    error("Error: Processed file or Target file not found!");
end

[y_est, fs_p] = audioread(processed_file);
[y_tgt, fs_t] = audioread(files.target);
[y_int, fs_i] = audioread(files.interf);

% Ensure Sampling Rate Match
target_fs = 16000;
if fs_p ~= target_fs, y_est = resample(y_est, target_fs, fs_p); end
if fs_t ~= target_fs, y_tgt = resample(y_tgt, target_fs, fs_t); end
if fs_i ~= target_fs, y_int = resample(y_int, target_fs, fs_i); end

% Ensure Mono
y_est = y_est(:,1);
y_tgt = y_tgt(:,1);
y_int = y_int(:,1);

%% 3. ALIGNMENT (Cross-Correlation)
[c, lags] = xcorr(y_tgt, y_est);
[~, I] = max(abs(c));
delay = lags(I);

if delay > 0
    y_est = y_est(delay+1:end);
    y_tgt = y_tgt(1:length(y_est));
    y_int = y_int(1:length(y_est));
elseif delay < 0
    delay = -delay;
    y_tgt = y_tgt(delay+1:end);
    y_int = y_int(delay+1:end);
    y_est = y_est(1:length(y_tgt));
end

% Truncate to min length
min_len = min([length(y_est), length(y_tgt), length(y_int)]);
y_est = y_est(1:min_len);
y_tgt = y_tgt(1:min_len);
y_int = y_int(1:min_len);

%% 4. METRICS: OSINR & SIR (Physics)
% -------------------------------------------------------------------------
% Orthogonal Projection decomposition
eps = 1e-10;
tgt_n = y_tgt / (norm(y_tgt) + eps);
int_n = y_int / (norm(y_int) + eps);

alpha = dot(y_est, tgt_n);
beta  = dot(y_est, int_n);

e_target = alpha * tgt_n;
e_interf = beta * int_n;
e_noise  = y_est - e_target - e_interf;

P_t = sum(e_target.^2);
P_i = sum(e_interf.^2);
P_n = sum(e_noise.^2);

SIR  = 10 * log10(P_t / (P_i + eps));
SINR = 10 * log10(P_t / (P_i + P_n + eps));

%% 5. METRICS: ViSQOL & STOI
% -------------------------------------------------------------------------
fprintf("Calculating ViSQOL (Native MATLAB) & STOI...\n");
visqol_val = NaN;
stoi_val = NaN;

% ViSQOL
if exist('visqol', 'file') == 2
    try
        visqol_val = visqol(y_est, y_tgt, target_fs, 'Mode', 'speech');
    catch ME
        warning("ViSQOL failed: %s", ME.message);
    end
else
    warning("Native 'visqol' function not found in MATLAB path.");
end

% STOI
if exist('stoi', 'file') == 2
    try
        stoi_val = stoi(y_tgt, y_est, target_fs);
    catch ME
        warning("STOI failed: %s", ME.message);
    end
else
     warning("STOI function not found. Ensure 'stoi' is in your path.");
end

%% 6. REPORT
fprintf("\n======================================\n");
fprintf(" EVALUATION RESULTS: %s\n", processed_file);
fprintf("======================================\n");
fprintf(" SIR    : %.2f dB\n", SIR);
fprintf(" SINR   : %.2f dB\n", SINR);
fprintf(" STOI   : %.4f\n", stoi_val);
fprintf(" ViSQOL : %.4f\n", visqol_val);
fprintf("======================================\n");
